### PR TITLE
Added code to parse podcast episode descriptions from HTML to plain t…

### PR DESCRIPTION
**Pull request by brian-doherty**
…ext.

### CODE REVIEW

**Comment by brian-doherty** [comment]
Fxies issue #349

**Comment by sentriz** [comment]
thanks! did you have a look at bluemonday though? this html2text seems to implement its own html parser which maybe isn't the best idea? or maybe we don't really care in this case

also it outputs markdown. do we want that?

**Comment by brian-doherty** [comment]
I tried bluemonday but it doesn't even leave a space between paragraph breaks, let alone a carriage return or two. This looks much better. FYI I chose the options to output text only rather than markdown.

**Comment by brian-doherty** [comment]
See the photos I pasted in the issue for comparison with bluemonday.

**Pull request merged**
