### PR TITLE
feat(ci): use ghcr and auto release

### PR DESCRIPTION
**Pull request by jef**
### Description

- Pushes images to GitHub Container Registry (GHCR) to deprecate Docker Hub
- Auto releases for nightly
- Auto releases for new release
- Auto maintained `CHANGELOG.md`

### Demo

- [Release run (not yet release)](https://github.com/jef/gonic/actions/runs/744980422)
- [Nightly Release run](https://github.com/jef/gonic/actions/runs/744980420)
	- This will normally happen 0:00 UTC and workflow dispatches, but can optionally be done every commit to `master`. (This is what is the behavior in this demo.)
- [PR Created after merge to `master`](https://github.com/jef/gonic/pull/2)
- [Release run (released with PR)](https://github.com/jef/gonic/actions/runs/744991974)
- [GitHub Container Registry (GHCR)](https://github.com/users/jef/packages/container/package/gonic)
    - [versions](https://github.com/users/jef/packages/container/gonic/versions)
	- [nightly](https://github.com/users/jef/packages/container/gonic/2188515?tag=nightly)
	- [v0.13.0](https://github.com/users/jef/packages/container/gonic/2007213?tag=v0.13.0)
	- [latest](https://github.com/users/jef/packages/container/gonic/2007213?tag=latest)
- [Release Page](https://github.com/jef/gonic/releases/tag/v0.13.0)

What it looks like when it pulls down:

```
$ docker pull ghcr.io/jef/gonic:latest 
latest: Pulling from jef/gonic
4c0d98bf9879: Already exists 
911dbe0279a4: Pull complete 
f66d3d929bfe: Pull complete 
d6d3bad5d561: Pull complete 
Digest: sha256:555f0e5ab2a191ab605c3184fc9b0afe003e994004a6e9fad312497cec94ea0e
Status: Downloaded newer image for ghcr.io/jef/gonic:latest
ghcr.io/jef/gonic:latest

$ docker run --rm -it ghcr.io/jef/gonic:latest gonic --version
v0.13.0
```

```
$ docker pull ghcr.io/jef/gonic:nightly       
nightly: Pulling from jef/gonic
4c0d98bf9879: Already exists 
4dee72d15ab4: Pull complete 
4a25032b7e30: Pull complete 
b15599f7c59a: Pull complete 
Digest: sha256:1bbb7ddbf1c264f45715ed1a8504529fe93acdba8e24d4e0a01b9d133a056c99
Status: Downloaded newer image for ghcr.io/jef/gonic:nightly
ghcr.io/jef/gonic:nightly

$ docker run --rm -it ghcr.io/jef/gonic:nightly gonic --version
v0.13.0-nightly
```

### Dependencies

A new secret must be added to the repository named `CR_PAT`.

### CODE REVIEW

**Comment by jef** [comment]
Here is some related documentation that helps release-please do it's job correctly:

- [release-please-action](https://github.com/google-github-actions/release-please-action)
- [Conventional Commits v1.0.0](https://www.conventionalcommits.org/en/v1.0.0/)

**Comment by sentriz** [comment]
hi! thanks very much for this change

- i like the idea of using ghcr for images. centralising here and not pushing stuff off dockerhub
- automatic change log based on commit conventions seems very cool

but some questions/concerns i have regarding this pr:

- it seems like the version.go file must be updated from `v0` before tests should run. eg. when working locally which could be annoying. though probably in this case, the test data shouldn't be depending on the version. i could update the tests to ignore the version field perhaps  
- peoples existing docker installations are expecting dockerhub images tagged with `sentriz/gonic`. but now it seems everyone would have to change to `ghcr.io/sentriz/gonic`. any ideas on what could be done here?
- the other dockerhub workflow still exists at `.github/workflows/image.yml`, this one builds for platforms like `linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7` with buildx/qemu and pushes to dockerhub. is it possible to do a similar thing here?

thanks!

cc @onedr0p ☺️

**Comment by jef** [comment]
Great questions! I'm glad you like the idea and I'm definitely missing a few things in this PR to make fully mergeable, so this is a good starting point.

> it seems like the version.go file must be updated from v0 before tests should run. eg. when working locally which could be annoying. though probably in this case, the test data shouldn't be depending on the version. i could update the tests to ignore the version field perhaps

I'm concerned about this as well. As I'm not 100% on what I wanted to do here, but I wanted to at least demo what this would look like.

I believe this is also a concern for those who perhaps run this via `go get` or through one of the package managers -- the version is not committed, thus the version wouldn't appear.

This could be alleviated a few different ways, but that's for later.

> peoples existing docker installations are expecting dockerhub images tagged with sentriz/gonic. but now it seems everyone would have to change to ghcr.io/sentriz/gonic. any ideas on what could be done here?

Short answer: probably not. Long answer: I don't think so, as there isn't a way (AFAIK) to link these images since they're on different registries.

That being said, it's not uncommon for folks to start using a new container registry (thinking of Linux Server's migration here). If folks want to keep using an old image on Dockerhub, I suppose there isn't anything stopping them unless you deleted the images. But I suppose it would be wise to put some disclaimer in the README for a month or so as things settle.

> the other dockerhub workflow still exists at .github/workflows/image.yml, this one builds for platforms like linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7 with buildx/qemu and pushes to dockerhub. is it possible to do a similar thing here?

We could totally do this! This would be the easiest thing to update. I can create a matrix of builds to push out GHCR.

**Comment by onedr0p** [comment]
Great addition @jef I recently made the transition to GHCR over at https://github.com/k8s-at-home/container-images and cannot be happier. Feel free to steal anything there if it helps :)

**Comment by jef** [comment]
Updated the visibility to the packages so you can actually see them now.

As for updating, what do you think our next steps should be so we can merge this in? (Aside from the conflicts).

**Comment by sentriz** [comment]
cool thanks! 

IMO the most important thing would be building images for arm etc. like the other `image` action

after that, solving the `version` issue would be nice. my initial thoughts would be make things really simple
- no version.go file (instead maybe instead a `go build -ldflags "-X main.VERSION=$VERSION"` if VERSION were some docker build arg from `needs.release-please.outputs.tag_name`
- having the tests ignore the `gonicVersion` field (or even just not returning it all over the subsonic api)
- define `main.VERSION` as "development" as a fallback for `go get` users `¯\_(ツ)_/¯`

then after that, notifying users about a migration in their configs from sentriz/gonic -> whatever/gonic
- probably a static warning banner on the gonic admin UI would be fine like "hi, warning, if you're using sentriz/gonic please move to whatever/"

i'd be happy to work on either of these changes too if needs be :+1: 

thoughts?

**Comment by jef** [comment]
I think these are all pretty reasonable requests. Once I build out some sample images and pushes the GHCR, then I'll remove my workflow secret, that way I can enable the edits from maintainers.

image

**Comment by sentriz** [comment]
hey, I spend some time getting to know ghcr and release-please this week and it's been really nice :+1: (was testing it on a different repo - invited you if you're interested) so I'm definitely gonna spend some time on the stuff above this weekend to get this merged

**Comment by sentriz** [comment]
opened on a PR at jef/gonic https://github.com/jef/gonic/pull/3

**Comment by sentriz** [comment]
hey, I'm not going to have time to work on projects much tomorrow or next week so I hope you don't mind, I pushed your commits and my changes already, and seems to be working well :)

generated PR https://github.com/sentriz/gonic/pull/138
and then https://github.com/users/sentriz/packages/container/package/gonic

going to close this now, if you have any comments / suggestions about the changes I made please do let me know

thanks very much for this :)

**Comment by onedr0p** [comment]
@sentriz you'll need to make the container image public. Github defaults any first push of images as private.

**Comment by jef** [comment]
Sorry about that, I have been on vacation, but this is great news! Sorry for the delay, glad everything turned out well :)

**Comment by jef** [comment]
Sounds good to me!

**Pull request closed without merging**
