### PR TITLE
Added support for podcast episodes in both playlists and play queues.

### PR DESCRIPTION
**Pull request by brian-doherty**

### CODE REVIEW

**Comment by sentriz** [comment]
cheers Brian! gonna do a release first the then ship this one at a .1

**Comment by sentriz** [comment]
hey, sorry for the delay. I'm traveling abroad at the moment. will have a look when I'm back late January. cheers

**Comment by brian-doherty** [comment]
No worries, and good for you.

**Comment by sentriz** [comment]
looks great thanks! i just rebased and pushed to master. and one small change splitIds -> splitIDs

cheers :+1:

**Pull request closed without merging**
