### PR TITLE
feature: add tini to dockerfile

### PR DESCRIPTION
**Pull request by onedr0p**
tini is a neat little `init`

https://github.com/krallin/tini

Benefits? See here

https://github.com/krallin/tini/issues/8

### CODE REVIEW

**Comment by zesoft23** [comment]
Random drop-in, but is it more worthwhile to add `tini` as a default argument in the README? `tini` has been built in since [Docker 19](https://github.com/krallin/tini) by adding the `--init` flag to `docker run`. It [can be used](https://stackoverflow.com/questions/50356032/whats-the-docker-compose-equivalent-of-docker-run-init#50357065) in `docker-compose` too. Seems more helpful to place the dependency on docker vs. integrating into the project. Just my 2 cents!

**Comment by onedr0p** [comment]
This isn't the case in Kubernetes, where we can use cri-o or containerd not just the Docker CRI.

**Comment by zesoft23** [comment]
Ah awesome, I had no idea it wasn't across the whole Docker CRI. Good luck with the PR!

**Comment by sentriz** [comment]
makes sense, thanks!

**Pull request merged**
