### PR TITLE
Added error case for when DownloadEpisode is called via API and podcast is already downloaded

### PR DESCRIPTION
**Pull request by brian-doherty**

### CODE REVIEW

**Comment by sentriz** [comment]
@lxea thoughts on this one

**Comment by lxea** [comment]
This seems fine to me, sometimes it can be useful to redownload stuff when a response is an error page which was happening to me with some feed hosts, this should probably just be handled properly by trying to parse the mp3 or checking the staus code or something

**Comment by brian-doherty** [comment]
FYI without this fix I was getting multiple copies of the same podcast with different filenames:

image

**Comment by sentriz** [comment]
thanks :+1: squashed and added

@lxea does this mean that we don't need the rename `(1)` `(2)` logic now?

**Pull request closed without merging**
