### PR TITLE
Added code to trigger rescan of entire tree upon file removal to clea…

### PR DESCRIPTION
**Pull request by brian-doherty**
…n as needed.

### CODE REVIEW

**Comment by brian-doherty** [comment]
@sentriz FYI the linter failed with a bunch of tar errors that I don't think have anything to do with my change. Do you have any idea what happened?

**Comment by brian-doherty** [comment]
@sentriz FYI the linter failed with a bunch of tar errors that I don't think have anything to do with my change. Do you have any idea what happened?

**Comment by sentriz** [comment]
ooh nice one , looks good 👍 

also think we can just ScanAndClean(ScanOptions{}) since IsFull will initialised to false anyway

> @sentriz FYI the linter failed with a bunch of tar errors that I don't think have anything to do with my change. Do you have any idea what happened?

yeah musttag, would you mind excluding that rule/longer from the .golangci lint config? I'm only on my phone atm

**Comment by sentriz** [comment]
this guy can go https://github.com/sentriz/gonic/blob/38ab0b0929660e76959b973eb5941f7104ee77dd/.golangci.yml#L48

**Comment by brian-doherty** [comment]
I made the change but lint is still failing with a ton of "Cannot open: File exists" errors. Here's how it starts:

Checking for go.mod: go.mod
  Received 237012410 of 241206714 (98.3%), 225.8 MBs/sec
  Cache Size: ~230 MB (2412067[14](https://github.com/sentriz/gonic/pull/496/checks#step:5:15) B)
  /usr/bin/tar -xf /home/runner/work/_temp/1e007a1e-b75a-464f-8a56-96a109222e67/cache.tzst -P -C /home/runner/work/gonic/gonic --use-compress-program unzstd
  Received 241206714 of 241206714 (100.0%), 114.9 MBs/sec
  /usr/bin/tar: ../../../go/pkg/mod/google.golang.org/protobuf@v1.28.0/LICENSE: Cannot open: File exists
  /usr/bin/tar: ../../../go/pkg/mod/google.golang.org/protobuf@v1.28.0/.github/workflows/test.yml: Cannot open: File exists
  /usr/bin/tar: ../../../go/pkg/mod/google.golang.org/protobuf@v1.28.0/README.md: Cannot open: File exists
  Error: /usr/bin/tar: ../../../go/pkg/mod/google.golang.org/protobuf@v1.28.0/cmd/protoc-gen-go/annotation_test.go: Cannot open: File exists
  Error: /usr/bin/tar: ../../../go/pkg/mod/google.golang.org/protobuf@v1.28.0/cmd/protoc-gen-go/main.go: Cannot open: File exists
  Error: /usr/bin/tar: ../../../go/pkg/mod/google.golang.org/protobuf@v1.28.0/cmd/protoc-gen-go/testdata/imports/fmt/m.pb.go: Cannot open: File exists

**Comment by brian-doherty** [comment]
And here is the final error:

  Running [/home/runner/go/bin/golangci-lint run --out-format=github-actions --timeout=5m] in [] ...
  Error: File is not `gofmt`-ed with `-s` (gofmt)
  
  Error: issues found
  Ran golangci-lint in 3437ms

**Comment by sentriz** [comment]
yeah it always prints those errors not sure why. I think you just need to rum gofmt

**Comment by brian-doherty** [comment]
Excuse my ignorance, but run gofmt where?

**Comment by sentriz** [comment]
try $ gofmt -w scanner/scanner.go

**Comment by brian-doherty** [comment]
That did it! Thanks!

**Comment by sentriz** [comment]
thanks!

**Pull request merged**
