### PR TITLE
feat: implement lyrics

### LINKED ISSUE #371: `.lrc` lyrics?
I've noticed the Subsonic protocol supports lyrics. I have a couple `.lrc` files lying around that I'd like to add to gonic to complete my music collection, especially with certain streaming services considering paywalling time-synced lyrics. My suggestion is to have the `.lrc` file have the same name as the audio file, minus its extension and plus `.lrc`. An example using the folder structure in the README:
```
music
├── drum and bass
│   └── Photek
│       └── (1997) Modus Operandi
│           ├── 01.10 The Hidden Camera.flac
│           ├── 01.10 The Hidden Camera.lrc
│           ├── 02.10 Smoke Rings.flac
│           ├── 02.10 Smoke Rings.lrc
│           ├── 03.10 Minotaur.flac
│           ├── 03.10 Minotaur.lrc
│           └── folder.jpg
```

The `.lrc` format is super easy to deal with, it's just plaintext with timestamps. There are some optional tags at the beginning of lyric files, check out [the Wikipedia page](https://en.wikipedia.org/wiki/LRC_(file_format)) for a good list.
```
[00:01.099]Hello world
```

### PR DESCRIPTION
**Pull request by TorchedSammy**
closes #371 

Implements both /getLyrics and OpenSubsonic [/getLyricsBySongId](https://opensubsonic.netlify.app/docs/endpoints/getlyricsbysongid/)

TODO:
- [ ] /getLyrics
  - [ ] Use artist in search for songs
  - [ ] Embedded
  - [x] .lrc
- [ ] /getLyricsBySongId
  - [ ] Embedded
  - [x] .lrc

### CODE REVIEW

**Comment by duckfromdiscord** [comment]
Awesome!

**Comment by duckfromdiscord** [comment]
I'm glad you also implemented `/getLyrics` since one of the apps I use is not maintained much anymore but does have support for it.

**Comment by TorchedSammy** [comment]
Works in Sonixd: 
Does not seem to work in Symfonium.

Should /getLyrics also return the timestamps as they are from the lrc file? I assume the current behavior is the correct one, where it's just the test, but some clients probably parse it from /getLyrics while some wouldn't.

**Comment by duckfromdiscord** [comment]
> Should /getLyrics also return the timestamps as they are from the lrc file?

No, see the `getLyrics` example: https://www.subsonic.org/pages/inc/api/examples/lyrics_example_1.xml

**Comment by TorchedSammy** [comment]
Should this also pick up .txt files? I noticed that [lrcget](https://github.com/tranxuanthang/lrcget) will download unsynced lyrics as .txt files.

**Comment by sentriz** [comment]
this looks great. i think we can get stuff merged incrementally here wdyt? for example just shipping support fr .lrc files first in one PR

**Comment by TorchedSammy** [comment]
I can exclude the embedded lyrics but can you give some guidance on how to query the artist in the database for /getLyrics search to be done?

**Comment by sentriz** [comment]
@TorchedSammy hi sorry for delay. regarding quering for artist, maybe ServeGetTopSongs could help. it does 

```go
	artistName, err := params.Get("artist")
	if err != nil {
		return spec.NewError(10, "please provide an `artist` parameter")
	}
	var artist db.Artist
	if err := c.dbc.Where("name=?", artistName).Find(&artist).Error; err != nil {
		return spec.NewError(0, "finding artist by name: %v", err)
	}

        // ...

        var tracks []*db.Track
	err = c.dbc.
                // ...
		Where("artists.id=?", artist.ID).
                // ...
		Error
```

**Comment by TorchedSammy** [comment]
looks like someone else is working on a pr for this, awesome.

**Pull request closed without merging**
