### PR TITLE
add webui-path option and mux handler

### PR DESCRIPTION
**Pull request by tbmale**

### CODE REVIEW

**Comment by tbmale** [comment]
I'm in no way a golang programmer but this is schratcing my itch and I'm using it for my local instance, so I tought...

**Comment by sentriz** [comment]
what's the usecase for this?

**Comment by tbmale** [comment]
> what's the usecase for this?

There are several subsonic web frontends out there ([jamstash](https://github.com/tsquillario/Jamstash),[airsonic-refix](https://github.com/tamland/airsonic-refix),[subplayer](https://github.com/peguerosdc/subplayer), etc.)

By doing ```-webapi-path``` I can self-host the frontend from gonic.

**Comment by sentriz** [comment]
i would recommended having your reverse proxy with static file server host those. gonic can also read the GONIC_PROXY_PATH option to be aware of any path prefixes 

hosting from gonic may also make it responsible for any security implications there. such as hosting two sites on the same domain, one of which isnt sanitising user input

**Pull request closed without merging**
