### PR TITLE
Changed frequent album list to use total time played per album instea…

### LINKED ISSUE #285: Should "most played" list divide by track count?
The "most played" list tends to overweight really long albums (box sets especially) because it is sorted by track plays and they have so many track. I submit as a question -- should it divide by track count instead, to give a notion of which _albums_ you play the most?

### PR DESCRIPTION
**Pull request by brian-doherty**
…d of play count. Closes #285

### CODE REVIEW

**Comment by sentriz** [comment]
not near computer atm but seem to have a migration error

**Comment by sentriz** [comment]
do we need an AutoMigrate() at the top of the migration body?

**Comment by brian-doherty** [comment]
Huh, i didn't have any problem in my local dev. Am i missing an ALTER TABLE to add the column? I'd try something but I'm on the road.

**Comment by sentriz** [comment]
fixed now, i think

**Pull request merged**
